### PR TITLE
(un)check_all

### PR DESCRIPTION
**Pull request by ryanbaekr**
### Description
Added check_all and uncheck_all to checkboxtreeview.py

### CODE REVIEW

**Comment by ryanbaekr** [comment]
I also have a demo [here](https://github.com/ryanbaekr/ttkwidgets_checkboxtreeview_-un-check_all_demo)

**Comment by rdbende** [comment]
Nice! Looks good to me!

Just a few suggestions to make it less boilerplate. (Something's broken here, so I can't make a real review suggestion)

I think the methods could be simplified. Currently the root item is handled separately, but it could be moved to `aux` with some simple modification.

```python
def check_all(self):
    """Check all items."""

    def aux(item):
        if item:
            self.change_state(item, "checked")
        children = self.get_children(item)
        for c in children:
            aux(c)

        aux("")
```

Maybe also delete the duplicate methods, and use `functools.partialmethod` instead.

```python
def _set_state_to_all(self, state):
    def aux(item):
        if item:
            self.change_state(item, state)
        children = self.get_children(item)
        for c in children:
            aux(c)

        aux("")
        
check_all = functools.partialmethod(_set_state_to_all, "checked")
uncheck_all = functools.partialmethod(_set_state_to_all, "unchecked")
```

**Comment by OogieM** [comment]
My only comment is that I really want this funciton soon :-) I was going to have to write soemthing  as I'm using one of thse and need the check and uncheck all available.

**Comment by ryanbaekr** [comment]
> Nice! Looks good to me!
> 
> Just a few suggestions to make it less boilerplate. (Something's broken here, so I can't make a real review suggestion)
> 
> I think the methods could be simplified. Currently the root item is handled separately, but it could be moved to `aux` with some simple modification.
> 
> ```python
> def check_all(self):
>     """Check all items."""
> 
>     def aux(item):
>         if item:
>             self.change_state(item, "checked")
>         children = self.get_children(item)
>         for c in children:
>             aux(c)
> 
>         aux("")
> ```
> 
> Maybe also delete the duplicate methods, and use `functools.partialmethod` instead.
> 
> ```python
> def _set_state_to_all(self, state):
>     def aux(item):
>         if item:
>             self.change_state(item, state)
>         children = self.get_children(item)
>         for c in children:
>             aux(c)
> 
>         aux("")
>         
> check_all = functools.partialmethod(_set_state_to_all, "checked")
> uncheck_all = functools.partialmethod(_set_state_to_all, "unchecked")
> ```

Oh, is something broken? I used this in my own project and didn't run into any issues

**Comment by rdbende** [comment]
No, it isn't broken. These are just suggestions to improve the code quality.

**Comment by ryanbaekr** [comment]
Anything on my end holding this up?

**Comment by rdbende** [comment]
> Anything on my end holding this up?

Not really. Tests are missing for the two new methods, but those are not necessarily your job.
It's simply that the project maintainers don't have the time to do it (I'd willingly do it, but I don't have write access currently)

**Review by RedFantom — CHANGES_REQUESTED** [review]
Thank you for your pull request! It's small and I didn't miss the notification, both ingredients for a PR review.

I agree with @rdbende , a single function would be better and prevent code duplication. Either `partialmethod` can be used, or the more explicit
```python
def check_all(self):
    self._set_state_to_all("checked")
```
Both are okay for me. See also [rdbende's comment](https://github.com/TkinterEP/ttkwidgets/pull/96#issuecomment-1237703593).

If you could, a unittest would also be nice. Something along the lines of:
```python
def test_check_uncheck_all(self):
    # Create some items
    tree.check_all()
    self.assertTrue(all(tree.get_state(item) for item in tree.get_children()))
    tree.uncheck_all()
    # and so on
```
would be fine. I don't actually know if `tree.get_state` is the right function, it's been a while since I used the `CheckboxTreeview`.

**Comment by ryanbaekr** [comment]
Should be all good now

**Comment by ryanbaekr** [comment]
@RedFantom anything on my end holding this up?

**Review by rdbende — APPROVED** [review]

**Comment by ryanbaekr** [comment]
@RedFantom I have made the change you requested. Anything on my end holding this up?

**Review by rdbende — APPROVED** [review]

**Comment by ryanbaekr** [comment]
@rdbende should I just withdraw this PR and make a new one?

**Comment by rdbende** [comment]
Why would you do that?

**Comment by ryanbaekr** [comment]
> Why would you do that?

Since I have to wait for @RedFantom to see that I made the changes he requested

**Comment by ryanbaekr** [comment]
> Why would you do that?

Since I have to wait for @RedFantom to see that I made the changes he/she requested

**Comment by rdbende** [comment]
Yes, you have made the changes he requested, although for some reason Github doesn't recognize it and won't let me merge it.

**Comment by ryanbaekr** [comment]
> Yes, you have made the changes he requested, although for some reason Github doesn't recognize it and won't let me merge it.

So if I withdraw it and make a new one then you could merge it, right?

**Comment by rdbende** [comment]
Well, that could work, but that still wouldn't mean, that it will be released to Pypi, so I think it's better to wait for @RedFantom.

**Comment by ryanbaekr** [comment]
@RedFantom plz

**Review by RedFantom — APPROVED** [review]
Hey, thanks for this! Sorry, I was away on holiday for a while and just started a new job, so that held things up for a bit. I'll try to get this to PyPI soon.

**Comment by ryanbaekr** [comment]
Thank you!

**Comment by RedFantom** [comment]
`0.13.0` is available from PyPI!

**Pull request merged**
