### PR TITLE
Merge fromateli:example_script for unified example runner script

### PR DESCRIPTION
**Pull request by formateli**
run.py script was created in order to show all examples at once, creating a button for each example.
All examples files were modified, encapsulated in 'Example' class which allow the example to be run as script or to be called by run.py script.
ttk widgets module is added to path automatically by run.py.

### CODE REVIEW

**Comment by formateli** [comment]
Thank you for the reply, it is my first github contribution. I will make the changes required and summit them.

**Comment by formateli** [comment]
All changes submitted for review.

**Comment by RedFantom** [comment]
Thank you for opening a pull request, @formateli ! Before I will review your pull request in a line-by-line manner, I would like to discuss something.

Various Tkinter libraries indeed use this method of having an overview application that shows all the options of the library. To me, the examples are not only a way to show the capabilities of a widget but more so a quick and dirty way to show how it can be used in code by users, which is why they are also [included in the documentation](https://ttkwidgets.readthedocs.io/en/latest/examples/font/FontSelectFrame.html). Wrapping them in classes undermines this purpose somewhat, so personally, I would prefer if the runner script, which I think is a great idea by itself, rather than open a Toplevel, just ran the individual scripts. This way, there can both be a runner script and the scripts themselves are still as readable as I'd like them to be for the documentation.

I'd like to hear your opinion on this.

**Comment by formateli** [comment]
I totally agree, in fact I avoided the idea of create an 'ExampleMixin' class and make the example classes derive from it, which would make it more difficult for users to visualize its use. The problem I found when trying to run existing ones without modification from a single window was dealing with 2 or more tk instances. which led me to strange behaviors.
On the other hand, it is quite tedious to run the example scripts one by one to see how they look like.

**Comment by formateli** [comment]
After reconsiderations, I am going to refactor the run.py script to call each example with subprocess, this way the code of the examples will not be modified.

I will create a new pull request for this.

**Pull request closed without merging**
