### PR TITLE
Merge tkinterpp-dirtree into tkinterpp-merger

### PR DESCRIPTION
**Pull request by Dogeek**
### PR Details:
- Widget name: `DirTree`
- Author: Dogeek

### Description
A Directory viewer in a ttk::Treeview widget.

### Checklist
- [x] Widget in a separate file in the appropriate folder
- [ ] Widget functions properly on both Windows and Linux (Linux untested)
- [x] Widget code includes docstrings with parameter descriptions
- [x] Included an example file in `/examples`
- [x] Widget is covered by unitttests in `/tests`
- [x] Widget includes required assets files
- [x] Reference to widget in `AUTHORS.md`
- [ ] Entry in sphinx documentation

### CODE REVIEW

**Comment by Dogeek** [comment]
Checks are failing because of the assets, also I didn't update the Balloon tests to reflect its new name

**Comment by Dogeek** [comment]
@RedFantom I don't know why that error shows up, do you have an idea ? Idk if it's because of a duplicated theme or something

**Comment by RedFantom** [comment]
That is an error I have seen before, yet I do not know what causes it. I just deleted the line in question and rewrote it, which fixed the error.

**Comment by RedFantom** [comment]
For internal merges like these which do not go into either the `master` or `tkinterpp` branch, feel free to just use the git merge functionality. PRs are not necessary for them. Just make sure that whenever a widget is ready, it is separate from other functionality, so it can be merged into the `tkinterpp` branch with a PR.

**Comment by Dogeek** [comment]
Yeah, it's just that I thought that the `tkinterpp-merger` branch would act as a temporary `master` until every widget from tkinterpp has been integrated into the `ttkwidgets` ecosystem, hence why I intended on opening pull requests, since it exposes the changes (that will eventually be on the master branch) to everyone, and it's a good way to have a checklist of stuff to do.

**Pull request merged**
